# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target ‘qz’ do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for qztourist
pod 'AFNetworking'
pod 'SDWebImage'
pod 'YYModel'
pod 'Masonry'
pod 'SVProgressHUD'
pod 'pop'
pod 'AMap3DMap', '~> 4.1.0'
pod 'AMapNavi'  #导航 SDK
pod 'AMapLocation'  #定位 SDK
# 集成新浪微博
pod 'UMengUShare/Social/Sina'

# 集成微信
pod 'UMengUShare/Social/WeChat'

# 集成QQ
pod 'UMengUShare/Social/QQ'
end
